### ISSUE TITLE
not working in android studio

### ISSUE THREAD

**Issue by blazingdevil44** [de-jcup/xdocreport-testapplication#1]
**build.gradle**
plugins {
    id 'com.android.application'
}

android {
    compileSdk 31

    defaultConfig {
        applicationId "com.example.myapplication"
        minSdk 21
        targetSdk 31
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {

    implementation 'androidx.appcompat:appcompat:1.3.1'
    implementation 'com.google.android.material:material:1.4.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.0'
    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.3'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'

    implementation group: 'fr.opensagres.xdocreport', name: 'fr.opensagres.xdocreport.document.docx', version: '2.0.2' // msword docx
    implementation group: 'fr.opensagres.xdocreport', name: 'fr.opensagres.xdocreport.converter.docx.xwpf', version: '2.0.2' // converter dependency
}

**MainCode**

public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        ActivityCompat.requestPermissions(this, new String[]{Manifest.permission.WRITE_EXTERNAL_STORAGE},
                1000);

        File folder = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS);
        //After file browser open select file than selct phone than select word file
        Intent chooseFile = new Intent(Intent.ACTION_GET_CONTENT);
        chooseFile.setType("*/*");
        chooseFile = Intent.createChooser(chooseFile, "Choose a file");
        startActivityForResult(chooseFile, 10001);

    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, @Nullable Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if (requestCode == 10001) {
            if (resultCode == RESULT_OK) {
                Uri uri = data.getData();
                BlazeFileUtils blazeFileUtils = new BlazeFileUtils(this);
                String filePath = blazeFileUtils.getPath(uri);
//                Toast.makeText(this, ""+filePath, Toast.LENGTH_SHORT).show();
                File infilePath = new File(filePath);

                File outfilePath;
                outfilePath = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOCUMENTS);
                if (outfilePath == null || "".equals(outfilePath.getPath()) || !outfilePath.exists())
                    outfilePath = new File(Environment.getExternalStorageDirectory().getPath() + "/Documents");
                if (!outfilePath.exists()) {
                    outfilePath.mkdir();
                    Toast.makeText(getApplicationContext(), "not exist", Toast.LENGTH_SHORT).show();
                }
                File outFile = new File(outfilePath, "testDocX.pdf");
                Toast.makeText(this, ""+outFile, Toast.LENGTH_SHORT).show();

                /* read the example DOCX file: */
                //File docxExampleFile = ensureExamplePDFFileExists();

                try {
                    convertToPDF(infilePath, outFile);
                } catch (FileNotFoundException e) {
                    e.printStackTrace();
                } catch (XDocConverterException e) {
                    e.printStackTrace();
                }

            }
        }
    }

    private File ensureExamplePDFFileExists() {
        File docxExampleFile = new File("./src/main/resources/example.docx");
        if (!docxExampleFile.exists()) {
            throw new IllegalStateException("file does not exist:" + docxExampleFile.getAbsolutePath());
        }
        return docxExampleFile;
    }

    private void convertToPDF(File docxExampleFile, File tmpOutputPath)
            throws FileNotFoundException, XDocConverterException {
        /* convert to PDF */
        Options options = Options.getFrom(DocumentKind.DOCX).to(ConverterTypeTo.PDF);

        IConverter converter = ConverterRegistry.getRegistry().getConverter(options);

        InputStream in = new FileInputStream(docxExampleFile);
        OutputStream out = new FileOutputStream(tmpOutputPath);
        converter.convert(in, out, options);
    }
}

**Comment by de-jcup** [comment]
@blazingdevil44 : Sorry, I don't the time and also not enough information to "just fix this" for you. Also I would always try to guess what you could have done, configured etc. 

You should do following:
1. Create a github repository and commit + push there a complete Android Studio project which
- contains your example code
- contains all gradle files etc.
- fails in the same way as your production code

2. This project must be importable by current Android Studio (Arctic Fox) so
- easy for others to just fix it
- easy for other to understand the situation
- easy for other to see the problem

3. Create *in your repository* an issue and add
 - (relevant) Logcat entries
 - Failure-Stacktraces 
 - Description what exactly the problem is
 - link your github project /issue inside your stackoverflow entry at https://stackoverflow.com/questions/69113420/ms-office-files-to-pdf-in-java-using-apache-poi
 - optional: link your github issue in your github project inside this issue as well.

**Comment by blazingdevil44** [comment]
I have already found a way to it in android after days of sleepless night now i just have(i think) final error before complete and i cant seem to get pass

**Couldn't load messages: Can't find bundle for base name org.apache.xmlbeans.impl.regex.message**

full stackstrace is this
[Process: com.example.myapplication, PID: 24548
    java.lang.ExceptionInInitializerError
        at org.apache.xmlbeans.impl.regex.SchemaRegularExpression.forPattern(SchemaRegularExpression.java:32)
        at org.apache.xmlbeans.impl.schema.BuiltinSchemaTypeSystem.fillInType(BuiltinSchemaTypeSystem.java:1011)
        at org.apache.xmlbeans.impl.schema.BuiltinSchemaTypeSystem.<clinit>(BuiltinSchemaTypeSystem.java:208)
        at org.apache.xmlbeans.impl.schema.BuiltinSchemaTypeSystem.getNoType(BuiltinSchemaTypeSystem.java:1056)
        at org.apache.xmlbeans.XmlBeans.getNoType(XmlBeans.java:504)
        at org.apache.xmlbeans.XmlBeans.<clinit>(XmlBeans.java:517)
        at org.apache.xmlbeans.XmlBeans.typeLoaderForClassLoader(XmlBeans.java:425)
        at org.openxmlformats.schemas.drawingml.x2006.chart.ChartSpaceDocument$Factory.getTypeLoader(Unknown Source:23)
        at org.openxmlformats.schemas.drawingml.x2006.chart.ChartSpaceDocument$Factory.parse(Unknown Source:0)
        at org.apache.poi.xddf.usermodel.chart.XDDFChart.<init>(XDDFChart.java:155)
        at org.apache.poi.xwpf.usermodel.XWPFChart.<init>(XWPFChart.java:75)
        at org.apache.poi.xwpf.usermodel.XWPFRelation$$ExternalSyntheticLambda0.init(Unknown Source:2)
        at org.apache.poi.ooxml.POIXMLFactory.createDocumentPart(POIXMLFactory.java:61)
        at org.apache.poi.ooxml.POIXMLDocumentPart.read(POIXMLDocumentPart.java:684)
        at org.apache.poi.ooxml.POIXMLDocument.load(POIXMLDocument.java:180)
        at org.apache.poi.xwpf.usermodel.XWPFDocument.<init>(XWPFDocument.java:145)
        at com.example.myapplication.MainActivity.onActivityResult(MainActivity.java:83)
        at android.app.Activity.dispatchActivityResult(Activity.java:7633)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5038)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5086)
        at android.app.ActivityThread.-wrap20(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2071)
        at android.os.Handler.dispatchMessage(Handler.java:109)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7555)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)
     Caused by: java.lang.RuntimeException: Installation Problem???  Couldn't load messages: Can't find bundle for base name org.apache.xmlbeans.impl.regex.message, locale en_PK
        at org.apache.xmlbeans.impl.regex.RegexParser.setLocale(RegexParser.java:89)
        at org.apache.xmlbeans.impl.regex.RegexParser.<init>(RegexParser.java:78)
        at org.apache.xmlbeans.impl.regex.ParserForXMLSchema.<init>(ParserForXMLSchema.java:28)
        at org.apache.xmlbeans.impl.regex.RegularExpression.setPattern(RegularExpression.java:2996)
        at org.apache.xmlbeans.impl.regex.RegularExpression.setPattern(RegularExpression.java:3009)
        at org.apache.xmlbeans.impl.regex.RegularExpression.<init>(RegularExpression.java:2975)
        at org.apache.xmlbeans.impl.regex.SchemaRegularExpression.<init>(SchemaRegularExpression.java:27)
        at org.apache.xmlbeans.impl.regex.SchemaRegularExpression.<init>(SchemaRegularExpression.java:23)
        at org.apache.xmlbeans.impl.regex.SchemaRegularExpression$1.<init>(SchemaRegularExpression.java:44)
        at org.apache.xmlbeans.impl.regex.SchemaRegularExpression.buildKnownPatternMap(SchemaRegularExpression.java:43)
        at org.apache.xmlbeans.impl.regex.SchemaRegularExpression.<clinit>(SchemaRegularExpression.java:38)
        at org.apache.xmlbeans.impl.regex.SchemaRegularExpression.forPattern(SchemaRegularExpression.java:32) 
        at org.apache.xmlbeans.impl.schema.BuiltinSchemaTypeSystem.fillInType(BuiltinSchemaTypeSystem.java:1011) 
        at org.apache.xmlbeans.impl.schema.BuiltinSchemaTypeSystem.<clinit>(BuiltinSchemaTypeSystem.java:208) 
        at org.apache.xmlbeans.impl.schema.BuiltinSchemaTypeSystem.getNoType(BuiltinSchemaTypeSystem.java:1056) 
        at org.apache.xmlbeans.XmlBeans.getNoType(XmlBeans.java:504) 
        at org.apache.xmlbeans.XmlBeans.<clinit>(XmlBeans.java:517) 
        at org.apache.xmlbeans.XmlBeans.typeLoaderForClassLoader(XmlBeans.java:425) 
        at org.openxmlformats.schemas.drawingml.x2006.chart.ChartSpaceDocument$Factory.getTypeLoader(Unknown Source:23) 
        at org.openxmlformats.schemas.drawingml.x2006.chart.ChartSpaceDocument$Factory.parse(Unknown Source:0) 
        at org.apache.poi.xddf.usermodel.chart.XDDFChart.<init>(XDDFChart.java:155) 
        at org.apache.poi.xwpf.usermodel.XWPFChart.<init>(XWPFChart.java:75) 
        at org.apache.poi.xwpf.usermodel.XWPFRelation$$ExternalSyntheticLambda0.init(Unknown Source:2) 
        at org.apache.poi.ooxml.POIXMLFactory.createDocumentPart(POIXMLFactory.java:61) 
        at org.apache.poi.ooxml.POIXMLDocumentPart.read(POIXMLDocumentPart.java:684) 
        at org.apache.poi.ooxml.POIXMLDocument.load(POIXMLDocument.java:180) 
        at org.apache.poi.xwpf.usermodel.XWPFDocument.<init>(XWPFDocument.java:145) 
        at com.example.myapplication.MainActivity.onActivityResult(MainActivity.java:83) 
        at android.app.Activity.dispatchActivityResult(Activity.java:7633) 
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5038) 
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5086) 
        at android.app.ActivityThread.-wrap20(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2071) 
        at android.os.Handler.dispatchMessage(Handler.java:109) 
        at android.os.Looper.loop(Looper.java:166) 
        at android.app.ActivityThread.main(ActivityThread.java:7555) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963) ](url)
        
        **Main problem is this when its about to convert**
        
             Caused by: java.lang.RuntimeException: Installation Problem???  Couldn't load messages: Can't find bundle for base name org.apache.xmlbeans.impl.regex.message, locale en_PK
             
             im using apache poi 4.12 with xmlbeans 4.0.0
             
             any idea how to fix it i have been at this project for month i about to go crazy xD

**Comment by de-jcup** [comment]
My exmaple code is using the mentioned two gradle dependencies does lead to usage of Apache POI 5.0 with also xmlbeans 4.0.0 - so your setup must be still different.


But after just looking at the given stacktrace 
```
Caused by: java.lang.RuntimeException: Installation Problem??? Couldn't load messages: Can't find bundle for base name org.apache.xmlbeans.impl.regex.message, locale en_PK
at org.apache.xmlbeans.impl.regex.RegexParser.setLocale(RegexParser.java:89)
```
I jumped to following code fragment:
![image](https://user-images.githubusercontent.com/11644753/133861760-3d57b144-bf9a-4c49-9bd8-63196b4cd936.png)

They have just changed the code a bit at default branch at github:
https://github.com/apache/xmlbeans/blob/64ac868d0057e71eee07c428c6f7a888c20a9474/src/main/java/org/apache/xmlbeans/impl/regex/RegexParser.java#L86

but it will still throw a MissingResourceException (which is a runtime exception) when the resource bundle is not found.

I would check if your libraries at runtime still have the message*.properties files inside
(sources see https://github.com/apache/xmlbeans/tree/64ac868d0057e71eee07c428c6f7a888c20a9474/src/main/resources/typeimpl/org/apache/xmlbeans/impl/regex) 

AFAIK android studio projects do normally always use proguard to shrink the output libs etc. If at runtime no resource bundles are in your class loader available this could be the problem.

![image](https://user-images.githubusercontent.com/11644753/133862778-f8fe6fa6-92ed-448b-8441-4bd8654ba8d9.png)

You could also do (for testing): create inside your android studio project the missing message resources by using same package as the misssing one (this should work with Java 8...) :
`src/main/resources/org/apache/xmlbeans/impl/regex/message.properties` and copy all the missing content into
(the text with parser.parse.1=Wrong character..... ) 
At least you could check if this works and the pdf conversion works after this.
Maybe your proguard setup filters the resources while shrinking. I am not sure it's just an idea.
